plugins {
    id 'com.android.application'
}

android {
    namespace 'com.rongyu.xiangqi'
    compileSdk 34

    defaultConfig {
        applicationId 'com.rongyu.xiangqi'
        minSdk 21
        targetSdk 34
        versionCode 17
        versionName '1.5.0'
    }

    signingConfigs {
        release {
            storeFile file('../release.keystore')
            storePassword 'rongyu2026'
            keyAlias 'xiangqi'
            keyPassword 'rongyu2026'
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}